# Generated by Django 5.1 on 2025-02-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('color', models.CharField(max_length=255)),
                ('background_color', models.CharField(max_length=255)),
                ('body_style', models.IntegerField()),
                ('frame_style', models.IntegerField()),
                ('square_style', models.IntegerField()),
                ('create_date', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profile')),
            ],
        ),
    ]
