# Generated by Django 5.1 on 2025-02-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createqr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='body_style',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='frame_style',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='square_style',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
