# Generated by Django 5.1.5 on 2025-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createqr_app', '0002_alter_qrcode_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='body_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='frame_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='square_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
