# Generated by Django 5.1.5 on 2025-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createqr_app', '0003_alter_qrcode_body_style_alter_qrcode_frame_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
