# Generated by Django 5.1.5 on 2025-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createqr_app', '0004_alter_qrcode_create_date_alter_qrcode_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='type_qr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
