# Generated by Django 5.1.5 on 2025-02-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_profile_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_expires',
            field=models.DateTimeField(),
        ),
    ]
