# Generated by Django 5.1.5 on 2025-02-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_profile_subscription_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commerce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='commerce_cells',
            field=models.IntegerField(default=0),
        ),
    ]
