# Generated by Django 5.1.5 on 2025-03-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_profile_commerce_profile_commerce_cells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='commerce_cells',
            field=models.IntegerField(default=20),
        ),
    ]
